import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Sparkles, ArrowLeft, Wand2, Loader2, RefreshCw, Grid3X3 } from 'lucide-react';
import { GoogleGenAI } from '@google/genai';
import { STYLE_PRESETS, GenerationConfig } from '../types';
import { formatPrompt, cn } from '../lib/utils';
import { useAuth } from '../lib/AuthContext';
import { db, handleFirestoreError, OperationType, storage } from '../lib/firebase';
import { collection, addDoc, serverTimestamp, query, orderBy, limit, getDocs } from 'firebase/firestore';
import { ref, uploadString, getDownloadURL } from 'firebase/storage';

interface GenerationViewProps {
  key?: string;
  initialPrompt?: string;
  onGenerated: (url: string) => void;
  onBack: () => void;
}

export default function GenerationView({ initialPrompt, onGenerated, onBack }: GenerationViewProps) {
  const { user } = useAuth();
  const [recentPrompts, setRecentPrompts] = useState<string[]>([]);
  const [config, setConfig] = useState<GenerationConfig>({
    prompt: initialPrompt || '',
    style: STYLE_PRESETS[0].prompt,
    gridSize: '4x4',
    iconSize: '256x256'
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Fetch recent prompts on load
  useEffect(() => {
    if (user) {
      const fetchRecent = async () => {
        try {
          const q = query(
            collection(db, `users/${user.uid}/history`),
            orderBy('timestamp', 'desc'),
            limit(5)
          );
          const snapshot = await getDocs(q);
          setRecentPrompts(snapshot.docs.map(doc => doc.data().prompt));
        } catch (err) {
          console.error("Failed to fetch history", err);
        }
      };
      fetchRecent();
    }
  }, [user]);

  const handleGenerate = async () => {
    if (!config.prompt) return;
    
    setIsGenerating(true);
    setError(null);
    
    try {
      // Save history to Firebase if user is logged in
      if (user) {
        try {
          await addDoc(collection(db, `users/${user.uid}/history`), {
            prompt: config.prompt,
            timestamp: serverTimestamp()
          });
          setRecentPrompts(prev => [config.prompt, ...prev.slice(0, 4)]);
        } catch (err) {
          handleFirestoreError(err, OperationType.CREATE, `users/${user.uid}/history`);
        }
      }

      const genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const fullPrompt = formatPrompt(config);
      
      const response = await genAI.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: [{ parts: [{ text: fullPrompt }] }],
        config: {
          imageConfig: {
            aspectRatio: "1:1"
          }
        }
      });

      // Find the image part in the response
      let imageUrl = '';
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (imageUrl) {
        // Upload to Firebase Storage if user is authenticated
        if (user) {
          try {
            const storagePath = `users/${user.uid}/generations/${Date.now()}.png`;
            const storageRef = ref(storage, storagePath);
            await uploadString(storageRef, imageUrl, 'data_url');
            const downloadUrl = await getDownloadURL(storageRef);
            
            // Save metadata to Firestore
            await addDoc(collection(db, 'iconSets'), {
              ownerId: user.uid,
              prompt: config.prompt,
              style: config.style,
              gridSize: config.gridSize,
              iconSize: config.iconSize,
              imageUrl: downloadUrl,
              storagePath: storagePath,
              createdAt: serverTimestamp()
            });
            
            onGenerated(downloadUrl);
          } catch (err) {
            console.error("Storage/Firestore error:", err);
            onGenerated(imageUrl); // Fallback
          }
        } else {
          onGenerated(imageUrl);
        }
      } else {
        throw new Error("No image was generated by the model. Try a different prompt.");
      }
    } catch (err: any) {
      console.error("Generation Error:", err);
      setError(err.message || "Failed to generate image. Please check your API key and prompt.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute inset-0 flex bg-bg-dark h-full overflow-hidden"
    >
      <div className="w-72 bg-bg-panel border-r border-brand-border flex flex-col shrink-0">
        <div className="p-4 border-b border-brand-border flex items-center gap-2">
          <button 
            onClick={onBack}
            className="p-1.5 hover:bg-white/5 rounded-md text-brand-text-muted hover:text-white transition-all"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500">Config</span>
        </div>

        <div className="flex-1 overflow-y-auto p-4 space-y-6">
          <section>
            <h3 className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest mb-4">Generation Engine</h3>
            
            <div className="space-y-5">
              <div className="space-y-2">
                <label className="text-[11px] text-zinc-400 block ml-1 font-medium">Creative Brief</label>
                <textarea 
                  value={config.prompt}
                  onChange={(e) => setConfig({ ...config, prompt: e.target.value })}
                  placeholder="e.g. isometric potions..."
                  className="input-dark w-full h-32 resize-none leading-relaxed focus:border-brand-accent/40"
                />
              </div>

              <div className="space-y-2">
                <label className="text-[11px] text-zinc-400 block ml-1 font-medium">Style Preset</label>
                <select 
                  className="input-dark w-full appearance-none pr-8 cursor-pointer focus:border-brand-accent/40"
                  onChange={(e) => {
                    const preset = STYLE_PRESETS.find(p => p.name === e.target.value);
                    if (preset) setConfig({ ...config, style: preset.prompt });
                  }}
                >
                  {STYLE_PRESETS.map(p => (
                    <option key={p.id} value={p.name}>{p.name}</option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-2">
                  <label className="text-[11px] text-zinc-400 block ml-1 font-medium">Grid</label>
                  <select 
                    value={config.gridSize}
                    onChange={(e) => setConfig({ ...config, gridSize: e.target.value })}
                    className="input-dark w-full focus:border-brand-accent/40"
                  >
                    <option value="4x4">4x4</option>
                    <option value="8x8">8x8</option>
                    <option value="single">1x1</option>
                  </select>
                </div>
                <div className="space-y-2">
                  <label className="text-[11px] text-zinc-400 block ml-1 font-medium">Size</label>
                  <select 
                    value={config.iconSize}
                    onChange={(e) => setConfig({ ...config, iconSize: e.target.value })}
                    className="input-dark w-full focus:border-brand-accent/40"
                  >
                    <option value="256x256">256px</option>
                    <option value="512x512">512px</option>
                  </select>
                </div>
              </div>

              {recentPrompts.length > 0 && (
                <div className="pt-4 mt-2 border-t border-brand-border space-y-3">
                  <h4 className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest px-1">Recent History</h4>
                  <div className="space-y-1.5">
                    {recentPrompts.map((p, i) => (
                      <div 
                        key={i} 
                        onClick={() => setConfig({ ...config, prompt: p })}
                        className="text-[10px] text-zinc-400 p-2 bg-zinc-800/30 rounded border border-zinc-700/30 truncate cursor-pointer hover:border-zinc-500 hover:text-white transition-all mono"
                      >
                        {p}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {error && (
                <div className="p-3 bg-red-500/10 border border-red-500/20 rounded text-red-500 text-[10px] mono">
                  ERR: {error.toUpperCase()}
                </div>
              )}
            </div>
          </section>
        </div>

        <div className="p-4 border-t border-brand-border">
          <button
            onClick={handleGenerate}
            disabled={isGenerating || !config.prompt}
            className={cn(
              "btn-primary w-full py-2.5 text-xs uppercase tracking-widest flex items-center justify-center gap-2 shadow-lg shadow-brand-accent/10",
              (isGenerating || !config.prompt) && "opacity-30 cursor-not-allowed"
            )}
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                Working...
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5" />
                Generate Sheet
              </>
            )}
          </button>
        </div>
      </div>

      {/* Preview Area */}
      <div className="flex-1 canvas-bg relative flex flex-col">
        <header className="h-10 border-b border-brand-border px-4 flex items-center justify-between bg-bg-panel/50 backdrop-blur-sm">
          <div className="flex gap-4">
             <div className="flex items-center gap-1.5 mono text-[10px] text-zinc-500">
               <div className={cn("w-1.5 h-1.5 rounded-full", isGenerating ? "bg-amber-500 animate-pulse" : "bg-green-500")}></div>
               STATUS: {isGenerating ? "GENERATING" : "IDLE"}
             </div>
             <div className="mono text-[10px] text-zinc-500">ENGINE: GEMINI_FLASH_AUTO</div>
          </div>
        </header>
        
        <div className="flex-1 flex items-center justify-center p-12">
          {isGenerating ? (
             <div className="max-w-md w-full space-y-6 text-center">
               <div className="w-20 h-20 bg-brand-accent/10 rounded-full flex items-center justify-center mx-auto relative">
                 <div className="absolute inset-0 rounded-full border-2 border-brand-accent/20 border-t-brand-accent animate-spin" />
                 <Wand2 className="w-8 h-8 text-brand-accent" />
               </div>
               <div className="space-y-2">
                 <h2 className="text-sm font-bold uppercase tracking-widest">Architecting Canvas</h2>
                 <p className="text-[11px] text-zinc-500 mono uppercase">Synthesizing consistent visual styles across grid coordinates...</p>
               </div>
             </div>
          ) : (
            <div className="max-w-md text-center space-y-4">
               <div className="w-16 h-16 rounded bg-zinc-800/50 flex items-center justify-center mx-auto border border-brand-border text-zinc-600">
                 <Grid3X3 className="w-8 h-8" />
               </div>
               <p className="text-zinc-500 text-[11px] mono uppercase leading-loose">
                 Enter a brief on the left to begin asset synthesis.<br/>
                 The engine will generate a consistent {config.gridSize} layout.
               </p>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}
